#Data set generated by "data_prep.Rmd"

initialPrediction <- readRDS("./data/initial-prediction.RDS")
freq2_with_stop <- readRDS("./data/freq2_with_stop.RDS")
freq3_with_stop <- readRDS("./data/freq3_ultra.RDS")
freq4_with_stop <- readRDS("./data/freq4_ultra.RDS")

match_predict2 <- function(userInput, ngrams) {

    ############# Ngrams = 4
    if(ngrams > 3) {  # Handle cases with longer than 3 words
        #1 exact match
        user_input_limit3 <- paste(userInput[length(userInput)-2], userInput[length(userInput)-1], userInput[length(userInput)])
        data_tokens <- freq4_with_stop %>% filter(variable == user_input_limit3)
        if(nrow(data_tokens) >= 1) {
            #already in order:  setorder(data_tokens, -percent)
            #print("freq4_with_stop")
            return(data_tokens$outcome[1:3])
        }
        #3 backoff to 3 grams
        return(match_predict2(userInput, ngrams - 1))
    }

    ############# Ngrams = 3

    if(ngrams == 3) {
        user_input_limited <- paste(userInput[length(userInput)-1], userInput[length(userInput)])
        data_tokens <- freq3_with_stop %>% filter(variable == user_input_limited)
        if(nrow(data_tokens) >= 1) {
            #already in order:  setorder(data_tokens, -percent)
            #print("freq3_with_stop")
            return(data_tokens$outcome[1:3])
        }
        #Backoff
        return(match_predict2(userInput, ngrams - 1))
    }

    ############# Ngram = 2

    if(ngrams < 3) {
        user_input_limited <- userInput[length(userInput)]
        data_tokens <- freq2_with_stop %>% filter(variable == user_input_limited)
        #if(nrow(data_tokens) >= 1) {
        #already in order setorder(data_tokens, -percent)
        #print("freq2_with_stop")
        return(data_tokens$outcome[1:3])
        #}
        #Backoff
        #return(match_predict(userInput, ngrams - 1))
    }

    ############# Ngram = 1  (Eliminated for speed considerations)

    return(NA)
}



clean_input <- function(input) {
    if(input == "" | is.na(input))
        return("")
    input <- tolower(input)
    input <- gsub("[0-9](?:st|nd|rd|th)", "", input, ignore.case=F, perl=T) #remove ordinal numbers
    input <- gsub("[.\\-!]", " ", input, ignore.case=F, perl=T) #remove punctuation
    input <- gsub("[^\\p{L}'\\s]+", "", input, ignore.case=F, perl=T) #remove punctuation, leaving '
    input <- gsub("^\\s+|\\s+$", "", input) #trim leading and trailing whitespace
    input <- stripWhitespace(input)
    if(input == "" | is.na(input))
        return("")
    input <- unlist(strsplit(input, " "))

    return(input)
}

predict <- function(input, word = 0) {

    if (input[1] == "") {
        output <- initialPrediction
    }
    else if (length(input) == 1) {
        output <- match_predict2(input, ngrams = 2)
    }
    else if (length(input) == 2) {
        output <- match_predict2(input, ngrams = 3)
    }
    else if (length(input) > 2) {
        output <- match_predict2(input, ngrams = 4)
    }

    if (word == 0)
        return(output)
    else if (word == 1)
        return(output[1])
    else if (word == 2)
        return(output[2])
    else if (word == 3)
        return(output[3])
}

shinyServer(function(input, output) {

    # original sentence
    output$userSentence <- renderText({input$userInput});

    # get predictions
    output$prediction1 <- reactive({predict(input$userInput, 1)})
    output$prediction2 <- reactive({predict(input$userInput, 2)})
    output$prediction3 <- reactive({predict(input$userInput, 3)})

})
